/** @file include/cbmimage/internal/dir.h \n
 * @author Spiro Trikaliotis \n
 * \n
 * @brief cbmimage internals
 *
 */
#ifndef CBMIMAGE_INTERNAL_DIR_H
#define CBMIMAGE_INTERNAL_DIR_H 1

enum {
	CBMIMAGE_DIR_ENTRY_TYPE_OFFSET       = 0x02u,
	CBMIMAGE_DIR_ENTRY_TRACK_OFFSET      = 0x03u,
	CBMIMAGE_DIR_ENTRY_SECTOR_OFFSET     = 0x04u,
	CBMIMAGE_DIR_ENTRY_NAME_OFFSET       = 0x05u,
	CBMIMAGE_DIR_ENTRY_SS_TRACK_OFFSET   = 0x15u,
	CBMIMAGE_DIR_ENTRY_SS_SECTOR_OFFSET  = 0x16u,
	CBMIMAGE_DIR_ENTRY_REL_RECORD_LENGTH = 0x17u,
	CBMIMAGE_DIR_ENTRY_BLOCK_COUNT_LOW   = 0x1Eu,
	CBMIMAGE_DIR_ENTRY_BLOCK_COUNT_HIGH  = 0x1Fu,

	CBMIMAGE_DIR_ENTRY_GEOS_INFO_TRACK   = 0x15u,
	CBMIMAGE_DIR_ENTRY_GEOS_INFO_SECTOR  = 0x16u,
	CBMIMAGE_DIR_ENTRY_GEOS_FILESTRUCTURE= 0x17u,
	CBMIMAGE_DIR_ENTRY_GEOS_FILETYPE     = 0x18u,
	CBMIMAGE_DIR_ENTRY_YEAR              = 0x19u,
	CBMIMAGE_DIR_ENTRY_MONTH             = 0x1Au,
	CBMIMAGE_DIR_ENTRY_DAY               = 0x1Bu,
	CBMIMAGE_DIR_ENTRY_HOUR              = 0x1Cu,
	CBMIMAGE_DIR_ENTRY_MINUTE            = 0x1Du,


	// CMD FD2000/FD4000 partition entries:
	CBMIMAGE_DIR_ENTRY_PARTITION_START_HIGH        = 0x16u,
	CBMIMAGE_DIR_ENTRY_PARTITION_START_LOW         = 0x17u,
	CBMIMAGE_DIR_ENTRY_PARTITION_BLOCK_COUNT_HIGH  = 0x1Eu,
	CBMIMAGE_DIR_ENTRY_PARTITION_BLOCK_COUNT_LOW   = 0x1Fu,

	CBMIMAGE_DIR_ENTRY_NEXT_ONE          = 0x20u,

	CBMIMAGE_DIR_ENTRY_NAME_LENGTH       = CBMIMAGE_DIR_ENTRY_SS_TRACK_OFFSET - CBMIMAGE_DIR_ENTRY_NAME_OFFSET,
};

enum {
	CBMIMAGE_HEADER_ENTRY_NAME_LENGTH    = 0x10u,
};

enum {
	CBMIMAGE_DIR_ENTRY_TYPE_MASK_TYPE   = 0x0Fu,
	CBMIMAGE_DIR_ENTRY_TYPE_MASK_LOCKED = 0x40u,
	CBMIMAGE_DIR_ENTRY_TYPE_MASK_CLOSED = 0x80u,
};

enum {
	CBMIMAGE_DIR_ENTRY_NAME_SHIFTSPACE  = 0xA0u,
};

#endif // #ifndef CBMIMAGE_INTERNAL_DIR_H
